### ISSUE TITLE
fix(README.md) Update API in README.md

### ISSUE THREAD

**Issue by darkcode357** [ail-project/PyLacus#40]
# Python client and module for Lacus

Use this module to interact with a [Lacus](https://github.com/ail-project/lacus) instance.

## Installation

```bash
pip install pylacus
```

### Command line

You can use the `pylacus` command:

```bash
$ pylacus -h
usage: pylacus [-h] --url-instance URL_INSTANCE [--redis_up] {enqueue,status,result} ...

Query a Lacus instance.

positional arguments:
  {enqueue,status,result}
                        Available commands
    enqueue             Enqueue a url for capture
    status              Get status of a capture
    result              Get result of a capture.

options:
  -h, --help            show this help message and exit
  --url-instance URL_INSTANCE
                        URL of the instance.
  --redis_up            Check if redis is up.

```

### Library

See [API Reference](https://pylacus.readthedocs.io/en/latest/api_reference.html)

# Example api metods 

## Status of a capture

```python
status = lacus.get_capture_status(uuid)
```

## Capture result

```python
result = lacus.get_capture(uuid)
```

# Full Example

This code utilizes the `redis` library and the `lacuscore` and `pylacus` modules to capture a web page using LacusCore.

**Note:** Make sure you have properly installed the required dependencies before executing this code.

```python
from redis import Redis
from lacuscore import LacusCore
from pylacus import PyLacus

redis = Redis()
lacus = PyLacus("http://xxx.xx.xxx.xx:7100/")
# Check if the Redis server is up
if lacus.redis_up():
    # Enqueue a capture for the URL(s) you want to capture
    uuid = lacus.enqueue(url='google.com')  # Replace 'google.com' with the desired URL(s)

    # Get the capture result based on the returned UUID
    result = lacus.get_capture(uuid)
    print(result)

```

Notes:
-  To manipulate the result of the capture as needed, you can use the "result" object, which is of the dictionary type
- Make sure you have a running instance of the Redis server.
- Replace the 'http://xxx.xx.xxx.xx:7100/' address with the correct LacusCore address.
@adulau @Rafiot @gallypette @SteveClement  @Terrtia

**Comment by Rafiot** [comment]
Do you want to do a pull request for that? It would be the easiest.
